Beginning of mapping palettes using PythonMagick
The line

blob = PythonMagick.Blob(myData, len(myData))

in pImageToMImage() currently throws a weird exception:

Boost.Python.ArgumentError: Python argument types in
    Blob.__init__(Blob, str, int)
did not match C++ signature:
    __init__(_object*, Magick::Blob)
    __init__(Magick::Blob {lvalue}, std::__cxx11::basic_string<char,
std::char_traits<char>, std::allocator<char> >)
    __init__(_object*)

The documentation specifies the second constructor very differently:

const void* data_, size_t length_

... which is what I'm trying to use, but instead I just brush up
against a bunch of C++-incarnate garbage.

The program takes an unacceptably long amount of time before it
throws this, too. I will probably need to do some optimisation once
I've fixed this.

Humm... A possibility to work around this is to go straight from
raw pixel data to an MImage in splitPImage(), so we don't need to
do this conversion at all which will also avoid the need for a
temporary file. Maybe I should go a step further and rip PIL out
of the program entirely.